### PR TITLE
feat(payment): PAYPAL-2624 Removing paypa pro payment method

### PR DESCRIPTION
**Pull request by bc-nick**
## What?

Removing paypa pro payment method

## Why?

This implementation is deprecated for `optimise one-page checkout`, because if we already have `one-page checkout` with `paypal-pro` connected and we decide to switch to `optimise one-page checkout`, this provider will be disabled by default

## Testing / Proof

Verified by switching from `one-page` checkout to optimised `one-page checkout`

@bigcommerce/team-checkout @bigcommerce/team-payments

### CODE REVIEW

**Review by serhii-tkachenko — CHANGES_REQUESTED** [review]
I don't really sure that we should do this now, since it might brake PayPal Payments Pro for current merchants who have this integration on their stores.

**Comment by animesh1987** [comment]
@serhii-tkachenko maybe we can do an AQI to check for the merchants that use this integration?

**Comment by serhii-tkachenko** [comment]
PayPal Payments Pro still can be onboarded when Feature_PaypalPaymentsProUS is enabled. Also I talked with Nick and he said, that we have merchants who still use this payment provider.

**Comment by animesh1987** [comment]
> PayPal Payments Pro still can be onboarded when Feature_PaypalPaymentsProUS is enabled. Also I talked with Nick and he said, that we have merchants who still use this payment provider.

Thanks. Is that available in OOPC? I know PaypalPro is available for legacy checkout, but legacy checkout doesn't use SDK integration.

**Comment by serhii-tkachenko** [comment]
> Is that available in OOPC?

@animesh1987 Yes. You can get an ability to setup PayPal Payments Pro for OOPC by enabling Feature_PaypalPaymentsProUS in Assets manager

**Pull request closed without merging**
