### PR TITLE
docs(shipping): fixes incorrect README instructions for getSelectedShippingOption

### PR DESCRIPTION
**Pull request by jeffthemaximum**
## What?
- fixes incorrect README instructions for getSelectedShippingOption

## Why?
- These docs misled me, so let's fix it!

## Testing / Proof

### CODE REVIEW

**Comment by jeffthemaximum** [comment]
AFAIK my `validate-commits` check is failing for this same reason: https://github.com/bigcommerce/checkout-sdk-js/pull/1137#issuecomment-877526877

**Review by bc-peng — APPROVED** [review]

**Comment by jeffthemaximum** [comment]
@bc-peng thanks for the approval. I'd love to merge this in, but the `validate-commits` CI check is failing, as described [above](https://github.com/bigcommerce/checkout-sdk-js/pull/1259#issuecomment-932494820).

**Comment by bc-peng** [comment]
> @bc-peng thanks for the approval. I'd love to merge this in, but the `validate-commits` CI check is failing, as described [above](https://github.com/bigcommerce/checkout-sdk-js/pull/1259#issuecomment-932494820).

Hi Jeff. It's come to our team's attention to optimise the commit validation. We will solve this with #1137 together. Please bear with us.

**Comment by animesh1987** [comment]
Hey @jeffthemaximum thanks for raising the fix. Can you please use `CHECKOUT-0000` or `GH-00` as part of the commit message i.e. `docs(shipping): CHECOUT-0000 fixes incorrect README instructions for getSelectedShippingOption` for now.

We are in process of updating our commit lint tool, which will make this process much smoother. 

Again sorry for the inconvenience caused.

**Pull request merged**
