### PR TITLE
feat(payment): INT-7557 BlueSnapDirect: Implement 3DS 2

### PR DESCRIPTION
**Pull request by mauricio-sg**
## What? [INT-7557](https://bigcommercecloud.atlassian.net/browse/INT-7557)
Implement [3DS in Hosted Payment Fields](https://developers.bluesnap.com/reference/3-d-secure-for-api#section-3-d-secure-in-hosted-payment-fields).

## Why?
To reduce eCommerce fraud by verifying a cardholder’s identity in real-time.

## Testing / Proof
https://user-images.githubusercontent.com/4843328/228607180-e3e5dc47-1926-490d-9871-dc90e151350b.mp4

---

@bigcommerce/checkout @bigcommerce/payments

## Depends on
👉 https://github.com/bigcommerce/bigcommerce/pull/51912

[INT-7557]: https://bigcommercecloud.atlassian.net/browse/INT-7557?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Review by david-intersys — APPROVED** [review]
LGTM 👍

**Review by bc-fergch — APPROVED** [review]
LGTM!

**Review by animesh1987 — APPROVED** [review]

**Comment by BC-BMedina** [comment]
💚 Tested!
QE Details:
3DS2 for Bluesnap Direct has been validated under the following scenarios:

- Successful with challenge
- Successful without challenge
- Failed with challenge
- Failed without challenge
- Unavailable
- Challenge buttons validation
- Challenge with discount
- Place orders with Challenge and transaction type as Auth Only + Post Order Actions (Capture, Void and Refunds)
- Place orders with Challenge and transaction type as Auth & Capture + Post Order Actions (Capture, Void and Refunds)
- Place orders with Challenge and Multicurrency (USD, EUR and JPY)
- Order with a Regular card
- Disabling 3DS Checkbox from settings page

Everything was working as expected, here you will find the evidence:
[INT-7557 Folder Evidence](https://drive.google.com/drive/folders/1hwGPfJTd050pfFV5pmONxVgWgCCOeikx?usp=share_link)

**Review by vmparra — APPROVED** [review]
LGTM 👍🏻

**Pull request merged**
