### PR TITLE
refactor(checkout): PI-2696 clenup PayPal integration packages spec e…

### PR DESCRIPTION
**Pull request by vitalii-koshovyi**
…rrors

## What?
Clenup PayPal integration packages spec errors

## Testing / Proof
image

@bigcommerce/team-checkout @bigcommerce/team-payments

### CODE REVIEW

**Review by serhii-tkachenko — APPROVED** [review]
Looks good to me! 👍

**Review by bc-peng — COMMENTED** [review]
I can still see some errors in the CircleCI test run, could you please check if they are missing issues?
```
PASS paypal-express-integration packages/paypal-express-integration/src/paypal-express-button-strategy.spec.ts (8.268 s)
ts-jest[ts-compiler] (WARN) packages/paypal-express-integration/src/paypal-express-script-loader.spec.ts:4:10 - error TS2305: Module '"./paypal-express-types"' has no exported member 'PaypalExpressTypes'.
```

**Comment by vitalii-koshovyi** [comment]
@bc-peng thanks for highlighting this errors, I missed them. Fixed.

**Review by bc-peng — APPROVED** [review]
Thank you for taking care of the clean-up job. 🙇🏻‍♂️

**Pull request merged**
