### PR TITLE
feat(payment): INT-6312 klarnav2 increase code coverage

### PR DESCRIPTION
**Pull request by bc-alejandroRodriguez**
## What? [INT-6312](https://bigcommercecloud.atlassian.net/browse/INT-6312)
Increase code coverage for klarnav2-payment-strategy

## Why?
Because there’re certain uses cases that must be covered.

## Testing / Proof
image

[Code coverage report for core_src_payment_strategies_klarnav2_klarnav2-payment-strategy.ts.pdf](https://github.com/bigcommerce/checkout-sdk-js/files/10701121/Code.coverage.report.for.core_src_payment_strategies_klarnav2_klarnav2-payment-strategy.ts.pdf)

@bigcommerce/checkout @bigcommerce/payments

[INT-6312]: https://bigcommercecloud.atlassian.net/browse/INT-6312?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by vmparra** [comment]
Hi @bc-alejandroRodriguez , thanks for doing this.

Can you please add a few screenshots about [missing paths](https://github.com/bigcommerce/checkout-sdk-js/files/10699624/Code.coverage.report.for.core_src_payment_strategies_klarnav2_klarnav2-payment-strategy.ts.pdf) being covered?

**Comment by bc-alejandroRodriguez** [comment]
> Hi @bc-alejandroRodriguez , thanks for doing this.
> 
> Can you please add a few screenshots about [missing paths](https://github.com/bigcommerce/checkout-sdk-js/files/10699624/Code.coverage.report.for.core_src_payment_strategies_klarnav2_klarnav2-payment-strategy.ts.pdf) being covered?

Hi @vmparra, I updated the description with a PDF of the coverage.

**Comment by vmparra** [comment]
> > Hi @bc-alejandroRodriguez , thanks for doing this.
> > Can you please add a few screenshots about [missing paths](https://github.com/bigcommerce/checkout-sdk-js/files/10699624/Code.coverage.report.for.core_src_payment_strategies_klarnav2_klarnav2-payment-strategy.ts.pdf) being covered?
> 
> Hi @vmparra, I updated the description with a PDF of the coverage.

[Awesome](https://media.giphy.com/media/Y9pvW54NNPRacOKg2D/giphy.gif)!

**Review by vmparra — APPROVED** [review]
LGTM 👍🏻

**Review by animesh1987 — APPROVED** [review]

**Pull request merged**
