### PR TITLE
fix(checkout): DATA-7883 segment

### PR DESCRIPTION
**Pull request by bc-maxym-parfenov**
## What?
[DATA-7883](https://jira.bigcommerce.com/browse/DATA-7883)

This PR is trying to fix an issue with missing transactions and products in GA for segment

## Testing / Proof
unit tests

@bigcommerce/checkout @bigcommerce/payments

### CODE REVIEW

**Comment by capsula4** [comment]
@bc-maxym-parfenov can you please remove the changes related to automatically generated files? All dist files, docs and changelogs

**Comment by TomA-R** [comment]
It'd be good to provide a more detailed title and description too

**Comment by PascalZajac** [comment]
Since today is Maxym's last day at BC, I suspect this is more of a WIP / draft.

**Comment by bc-maxym-parfenov** [comment]
Sure team, It's draft version, our team trying to test this .

**Comment by bc-leprik** [comment]
@PascalZajac please close this PR, this fix will be on another PR: https://github.com/bigcommerce/checkout-sdk-js/pull/1159

**Pull request closed without merging**
