### PR TITLE
feat(payment): INT-4893 Retrieve initialization data from Humm

### PR DESCRIPTION
**Pull request by josesonora**
## What? [INT-4893](https://jira.bigcommerce.com/browse/INT-4893)
Retrieve additional data related to the method before start processing the payment

## Why?
We need the processable value to be able to start the payment process, it will be determined by some configuration set by the merchant in the settings page

## Testing / Proof
image
image

ping @bigcommerce/apex-integrations @bigcommerce/payments

### CODE REVIEW

**Review by roberbnd — APPROVED** [review]
LGTM

**Comment by animesh1987** [comment]
Can we please merge the other PR and rebase this one?

**Comment by josesonora** [comment]
Hi @animesh1987 this PR is ready to be reviewed, could you please take a look at it? 🙇

**Review by animesh1987 — APPROVED** [review]

**Review by clopezh — APPROVED** [review]
lgtm

**Comment by josesonora** [comment]
Hi @animesh1987 , could you please review my changes related to the message translation? it's this commit afa9698afe63fdd6b09e7cb97abc6a37ae4ed8e1

**Review by animesh1987 — APPROVED** [review]

**Pull request merged**
